//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaTaller.Models.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idCliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> nro_dni { get; set; }
        public string Apellido { get; set; }
    }
}
