//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaTaller.Models.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int id_proveedor { get; set; }
        public string razon_social { get; set; }
        public Nullable<decimal> cuit { get; set; }
        public string direccion { get; set; }
    }
}
